version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    rebase-strategy: 'auto'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'gradle'
    directory: '/'
    rebase-strategy: 'auto'
    schedule:
      interval: 'daily'
