name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/build.gradle') }}

      - name: Gradle Build / Test
        run: ./gradlew clean build

